version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:0db67a6344313962a5488e05e7b9b143873a25ff
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine]
    default: nightly
  resource-class:
    type: string
    default: "small"

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          executor: << parameters.executor >>
          resource-class: << parameters.resource-class >>
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          needs-lfs: true
      - r-packages/deploy-package:
          executor: << parameters.executor >>
          resource-class: << parameters.resource-class >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger-revdeps:
          executor: << parameters.executor >>
          resource-class: << parameters.resource-class >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          plugins-branch: << pipeline.parameters.plugins-branch >>
          trigger-message: << pipeline.parameters.trigger-message >>
          triggered-packages: << pipeline.parameters.triggered-packages >>
