version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:alpha
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine, rocker_geo]
    default: nightly
  resource-class:
    type: string
    default: "small"

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build_and_check_package:
          executor: << pipeline.parameters.executor >>
          resource_class: << pipeline.parameters.resource_class >>
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote_deps: << pipeline.parameters.remote_deps >>
          needs_lfs: true
      - r-packages/deploy_package:
          executor: << pipeline.parameters.executor >>
          resource_class: << pipeline.parameters.resource_class >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
