# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: '**'
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
    
      - name: Create JSON payload
        if: always()
        run: |
          echo "${{runner.os}}"
          echo "${{matrix.config.r}}"
	  JSON_PAYLOAD=$(cat << EOF
	  {\"blocks\":[{
			\"type\": \"section\",
			\"text\": {
				\"type\": \"mrkdwn\",
				\"text\": \"Workflow ${{github.job}} in ${{github.repository}} has *failed*.\"
			},
			\"accessory\": {
				\"type\": \"button\",
				\"text\": {
					\"type\": \"plain_text\",
					\"text\": \"Job ${{github.job_id}}\",
					\"emoji\": true
				},
				\"value\": \"click_me_123\",
				\"url\": \"${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}\",
				\"action_id\": \"button-action\"
			}
		},
		{
			\"type\": \"divider\"
		},
		{
			\"type\": \"section\",
			\"text\": {
				\"type\": \"mrkdwn\",
				\"text\": \"Commit ${{github.sha}} by ${{github.actor}}.\"
			},
			\"accessory\": {
				\"type\": \"button\",
				\"text\": {
					\"type\": \"plain_text\",
					\"text\": \"View commit\",
					\"emoji\": true
				},
				\"value\": \"click_me_123\",
				\"url\": \"${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}\",
				\"action_id\": \"button-action\"
			}
		}
		EOF
		)
		echo "JSON_PAYLOAD<<EOF" >> $GITHUB_ENV
		echo "$JSON_PAYLOAD" >> $GITHUB_ENV
          	echo "EOF" >> $GITHUB_ENV
        shell: bash
    
      - name: Send success JSON data to Slack workflow
        id: slack
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "${{env.JSON_PAYLOAD}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send failure JSON data to Slack workflow
        id: slackfail
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "${{fromJSON(env.JSON_PAYLOAD)}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    
